# Copyright (c) 20224 Stogl Robotics Consulting UG (haftungsbeschränkt)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Source of this file are templates in
# [RosTeamWorkspace](https://github.com/StoglRobotics/ros_team_workspace) repository.
#
# Author: Dr. Denis
#

/**/controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    roomba_controller:
      type: roomba_controller/RoombaController

    gpio_command_controller:
        type: gpio_controllers/GpioCommandController





/**/roomba_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.235
    wheel_radius: 0.036
    command_timeout: 0.5
    velocity_rolling_window_size: 2
    position_feedback: true
    open_loop: false
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 0.977
    enable_odom_tf: true #done by ekf node


/**/gpio_command_controller:
  ros__parameters:
    type: gpio_controllers/GpioCommandController

    gpios:
      - main_brush
      - side_brush
      - vacuum
      - mode
      - led_bits
      - led_color
      - led_intensity

    command_interfaces:
      main_brush:
        - interfaces:
          - duty_cycle
      side_brush:
        - interfaces:
          - duty_cycle
      vacuum:
        - interfaces:
          - duty_cycle
      mode:
        - interfaces:
          - value
      led_bits:
        - interfaces:
          - value
      led_color:
        - interfaces:
          - value
      led_intensity:
        - interfaces:
          - value

    state_interfaces:
      main_brush:
        - interfaces:
          - duty_cycle
      side_brush:
        - interfaces:
          - duty_cycle
      vacuum:
        - interfaces:
          - duty_cycle
      mode:
        - interfaces:
          - value
      led_bits:
        - interfaces:
          - value
      led_color:
        - interfaces:
          - value
      led_intensity:
        - interfaces:
          - value
