# Copyright (c) 20224 Stogl Robotics Consulting UG (haftungsbeschränkt)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Source of this file are templates in
# [RosTeamWorkspace](https://github.com/StoglRobotics/ros_team_workspace) repository.
#
# Author: Dr. Denis
#

/**/controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    gpio_command_controller:
        type: gpio_controllers/GpioCommandController





/**/diff_drive_controller:
  ros__parameters:
    left_wheel_names:
      - robot2/left_wheel_joint
    right_wheel_names:
      - robot2/right_wheel_joint

    wheel_separation: 0.235
    wheel_radius: 0.036

    command_timeout: 0.5
    velocity_rolling_window_size: 5

    position_feedback: true
    open_loop: false

    enable_odom_tf: true
    tf_frame_prefix_enable: false

    odom_frame_id: robot2/odom
    base_frame_id: robot2/base_link

/**/gpio_command_controller:
  ros__parameters:
    type: gpio_controllers/GpioCommandController

    gpios:
      - robot2/main_brush
      - robot2/side_brush
      - robot2/vacuum
      - robot2/mode
      - robot2/led_bits
      - robot2/led_color
      - robot2/led_intensity

    command_interfaces:
      robot2/main_brush:
        - interfaces:
          - duty_cycle
      robot2/side_brush:
        - interfaces:
          - duty_cycle
      robot2/vacuum:
        - interfaces:
          - duty_cycle
      robot2/mode:
        - interfaces:
          - value
      robot2/led_bits:
        - interfaces:
          - value
      robot2/led_color:
        - interfaces:
          - value
      robot2/led_intensity:
        - interfaces:
          - value

    state_interfaces:
      robot2/main_brush:
        - interfaces:
          - duty_cycle
      robot2/side_brush:
        - interfaces:
          - duty_cycle
      robot2/vacuum:
        - interfaces:
          - duty_cycle
      robot2/mode:
        - interfaces:
          - value
      robot2/led_bits:
        - interfaces:
          - value
      robot2/led_color:
        - interfaces:
          - value
      robot2/led_intensity:
        - interfaces:
          - value